#:import MDDropdownMenu kivymd.uix.menu.MDDropdownMenu

<Volume>:
     BoxLayout:
        anchor_x: 'center'
        anchor_y: 'top'
        orientation: 'vertical'
        canvas.before:
            Color:
                rgba: 0.3, 0.3, 0.3, 1
            Rectangle:
                size: self.size
                pos: self.pos

        MDToolbar:
            title: "Volume for Solution"
            md_bg_color: app.theme_cls.primary_color
            elevation: 10
            left_action_items: [['arrow-left', lambda x: app.get_main_screen()]]
        Widget:
    BoxLayout:
            canvas:
                Color:
                    rgba: 0.3, 0.3, 0.3, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
            orientation: 'horizontal'
            size_hint_y: None
            height: dp(56)
            padding: dp(8)
            spacing: dp(16)

            MDRectangleFlatButton:
                id: solution_types
                text: 'Solution Type'
                size: 3 * dp(48), dp(48)
                on_release: MDDropdownMenu(items=root.SOLUTION_TYPES, width_mult=4).open(self)
            Widget:
